<MyBoxLayout>:
	show: show
	read: read
	type: type
	input: input
	read1: read1
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height
		
		Label: 
			id: show
			text: ''
			
		Label:
			id: read
			text: ''
			
		Label:
			id: type
			text: ''
			
		TextInput:
			id: input
			text: ''
			
		Button:
			text: "Okay"
			on_press: root.press()
			
		Label:
			id: read1
			text: ''
			